version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      jekyll-stack:
        patterns:
          - "jekyll*"
          - "kramdown*"
          - "rouge*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"