image: ruby:3.3

variables:
  JEKYLL_ENV: production
  BUNDLE_PATH: vendor/bundle

cache:
  paths:
    - vendor/bundle

before_script:
  - gem install bundler
  - bundle install --jobs $(nproc) "${FLAGS}"

pages:
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - main     # o master
