# _config.yml
title: "Blog de Enrique Verdes"
description: "Artículos técnicos y notas personales"
minimal_mistakes_skin: "air"
paginate: 7

author:
  name   : "Enrique Verdes"
  links:
    - label: "LinkedIn"
      url:  "https://www.linkedin.com/in/enriqueverdes/"
    - label: "GitHub"
      url:  "https://github.com/emverdes"

nav:
  - title: "Artículos técnicos"
    url:   /categories/tech/
  - title: "Libros & Música"
    url:   /categories/personal/
  - title: "Acerca de…"
    url:   /about/
